### ISSUE TITLE
Testing/forbidden functions/norminette

### ISSUE THREAD

**Issue by WSSMRKS** [WSSMRKS/42_minishell#102]

**Comment by WSSMRKS** [comment]
testing is tracked in 
https://docs.google.com/spreadsheets/d/1LHthQNXFy6PmVpydN8Z7ZL1BiNmmUZ_uQwInHyDV15A/edit?usp=sharing

**Comment by WSSMRKS** [comment]
ToFix:
- [ ] ls -l > file1 | cat -e > file2 | wc -l > file3	file 1 with no permissions	n	file 2 is empty	file 2 contains the output of ls-l	!	Close pipe when ls -l is encountering no permissions
- [ ] echo hello world | grep hello > output.txt		n	as expected	if no permissions (file error) output is passed to stdout	!	Close pipe when ls -l is encountering no permissions
- [ ] cat < input.txt | sort | uniq		n	if input.txt has no permissions error message: "bash: file2: Permission denied"	if input.txt has no permissions error message: "file2: Permission denied"	!	review error messages
- [ ] <<eof cat | cat >hd_output1	Test with everything including variables	n	\$PATH becomes $PATH	\$PATH stays \$PATH 
- [ ] cat | sjlfkdsjfs | ls	using SIGINT in cat	n	echo $? is 130	echo $? is 0
- [ ] pwd in nonexistent directory (deleted after entering) == segfault.
- [ ] cd not working with tilde ~; exitstatus not set properly after cd to nonexistent path or no permissions
- [ ] export including the variable "_"

Details:
https://docs.google.com/spreadsheets/d/1LHthQNXFy6PmVpydN8Z7ZL1BiNmmUZ_uQwInHyDV15A/edit?usp=sharing

**Comment by WSSMRKS** [comment]
Testing with eval sheet:

- [ ] exit with super long number doesn't do anything. Not even an error.
- [ ] ls cat and so on still working after unsetting PATH variable

**Comment by kjzl** [comment]
- [ ] check return values of exit with last exec return value 
- [ ] check return values when using ctrl+D in all scenarios (maybe we can copy&paste from exit builtin to repl?)

**Comment by WSSMRKS** [comment]
Done
