### ISSUE TITLE
Rewrite ft_repl

### ISSUE THREAD

**Issue by WSSMRKS** [WSSMRKS/42_minishell#59]
Due to the "exit" builtin there is almost no occasion left to exit the repl inside ft_repl

**Comment by WSSMRKS** [comment]
The exit builtin is working in a different way than before to be able to take arguments. This means the following two lines are never true:
	```
// if (ms->cmds && ms->cmds->cmd && strcmp("exit", ms->cmds->cmd->argv[0]) == 0)
	// 	return (MS_EOF);
```

**Comment by kjzl** [comment]
should be fine i think, the only thing the MS_EOF did trigger was a print of "exit" to the console, only thing is that resource freeing isnt cleanly integrated in our ft_free_all_exit yet, which also shouldnt be a problem though

**Comment by kjzl** [comment]
No further action needed, old code removed by commit c2d7144
