### ISSUE TITLE
in heredoc $VAR should be expanded except quotes are present in the delimiter.

### ISSUE THREAD

**Issue by WSSMRKS** [WSSMRKS/42_minishell#88]

**Comment by kjzl** [comment]
very tricky to implement, maybe somehow we need to integrate heredoc in the parser code.
In the later stages of parsing the information, about whether a word was in quotes or not, is lost.

**Comment by WSSMRKS** [comment]
Done and implemented. We just need to add a t_redir_type that indicates that there was some type of quote in the delimiter or an additional flag indicting that there were quotes in the dilimiter :+1: 
Not the most clean implementation but works. Needed to used a function of the tokenizer for variable expansion.

typedef enum	e_redir_type {
	redir_append,
	redir_here_doc,
	**//redir_hd_w_quotes,**
	redir_infile,
	redir_outfile,
}	t_redir_type;

**Comment by kjzl** [comment]
need to copy and change the str expand function to remove the backslash before dollar when not expanding a var

**Comment by kjzl** [comment]
Completed by commit e7a7cf88ba6026a02caa7340908696d9f60b0db5
