### ISSUE TITLE
Copy paste to heredoc not working

### ISSUE THREAD

**Issue by WSSMRKS** [WSSMRKS/42_minishell#94]
ms/maweiss@c4c2c1:~/mw/minishell/minishell_1st$ cat << EOF
> First Heredoc Test
EOF
> 
> 
> 
> 
> cat << EOF
First Heredoc Test
EOF
> ^C
> 
minishell: warning: here-document at line 6 delimited by end-of-file (wanted `EOF')
First Heredoc Test
EOF

cat << EOF
First Heredoc Test
EOF
ms/maweiss@c4c2c1:~/mw/minishell/minishell_1st$ cat << EOF
First Heredoc Test
EOF
> EOF
First: command not found

**Comment by WSSMRKS** [comment]
we need to update the parser to handle this. 
`c4c2c1% <<bla cat -e >out1
"cat | cat | ls"
"echo hello world | grep hello > output.txt"
"cat < input.txt | sort | uniq"
"find . -type f | xargs grep \"[ ]\" > todo_list.txt"
"mkdir new_folder | ls -l"
"tar -czf archive.tar.gz /new_folder | ls -l archive.tar.gz"
"echo $HOME > home_directory.txt"
bla`

this should result in a closed execution where the heredoc is complete and it just gets executed. We need to take a look at heredoc again.

**Comment by kjzl** [comment]
Easy fix I'd say
I have to change the parser to only process one line at a time, and inbetween the lines check for heredoc presence and then feed the remaining lines to the heredoc function. The Heredoc function will consume only as many lines as it needs and the parser will try to process any remaining ones.
With this program flow we would be able to allow to copy and paste commands like the following into minishell:
```
<< EOF cat
one
two
EOF
<< EOF2 cat
three
four
EOF2
```
